version: '3.4'
services:
    server:
        build: .
        container_name: server-core
        ports:
            - "25565:25565"
        volumes:
            - "band_minecraft_server:/server"
        tty: true

volumes:
  band_minecraft_server:
    external: true